{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-0.0.8.aar",
          "url": "flutter_secure_storage_release-0.0.8.aar",
          "size": 26282,
          "sha512": "608faba30c1313b9808f632bf709cca2991e3bd84f29cfe123092a77a46e72ba972d3a3c7bd1b65067d8417fd2c43abab562fa6eab4515359933ca7dd1b1560c",
          "sha256": "c637250f8ae361a466b0d4cbaaf0ed2ca5c2ffe0d5743dac7f082eb01a01332c",
          "sha1": "9731c0622275594830d9c757183d771c62ead5cb",
          "md5": "93d1847c68318e64a0545dcaf56d71e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-0.0.8.aar",
          "url": "flutter_secure_storage_release-0.0.8.aar",
          "size": 26282,
          "sha512": "608faba30c1313b9808f632bf709cca2991e3bd84f29cfe123092a77a46e72ba972d3a3c7bd1b65067d8417fd2c43abab562fa6eab4515359933ca7dd1b1560c",
          "sha256": "c637250f8ae361a466b0d4cbaaf0ed2ca5c2ffe0d5743dac7f082eb01a01332c",
          "sha1": "9731c0622275594830d9c757183d771c62ead5cb",
          "md5": "93d1847c68318e64a0545dcaf56d71e6"
        }
      ]
    }
  ]
}
