{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_release",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-0.0.8.aar",
          "url": "connectivity_plus_release-0.0.8.aar",
          "size": 9004,
          "sha512": "5d57e409e052c7e11bb2ec8cba611daca9d4e98f8191d36c6cfdf111c35cfd52cc33bb883668143e24cce30b1fd381abf0d99fd4b5276a89ad96f27d4d9855e1",
          "sha256": "86a7d62294bca68af0e9e1607b8de5a59f27d8835f7c38c3ed4044a5d2961a59",
          "sha1": "74514ba8b492a519d53d1971d172cc04a9e026f0",
          "md5": "7394ed478cc774fff86a06fcb0b7fc06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d44b5a94c976fbb65815374f61ab5392a220b084"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-0.0.8.aar",
          "url": "connectivity_plus_release-0.0.8.aar",
          "size": 9004,
          "sha512": "5d57e409e052c7e11bb2ec8cba611daca9d4e98f8191d36c6cfdf111c35cfd52cc33bb883668143e24cce30b1fd381abf0d99fd4b5276a89ad96f27d4d9855e1",
          "sha256": "86a7d62294bca68af0e9e1607b8de5a59f27d8835f7c38c3ed4044a5d2961a59",
          "sha1": "74514ba8b492a519d53d1971d172cc04a9e026f0",
          "md5": "7394ed478cc774fff86a06fcb0b7fc06"
        }
      ]
    }
  ]
}
